### ISSUE TITLE
appears to have found the back door

### ISSUE THREAD

**Issue by c0yax** [bokub/vanity-eth#40]
url : https://metrics.vanity-eth.tk/api/collect

```
cache: null
hostname: ""
language: "zh-CN"
referrer: ""
screen: "1920x1080"
url: "/C:/Users/Admin/Desktop/dist/index.html"
website: "9086c519-8c4a-4f8e-9dfe-daee3739238a"
```

**Comment by zhaocaijinbao1314** [comment]
Really？

**Comment by c0yax** [comment]
![](https://s3.bmp.ovh/imgs/2022/04/01/82df3972a099e23c.png)

Please explain what this is

**Comment by bokub** [comment]
Hello,

This has nothing to do with a "backdoor"

It's just a self-hosted [umami](https://umami.is/) server (privacy-focused analytics) to count the number of visitors.

As you can see in your screenshot:
- The only data sent to the analytics server are your language, the current URL, and the screen size
- The HTTP call is done only when you land on the page, before you generate anything, so even if I wanted to, I couldn't steal your private key because it doesn't exist yet

**Comment by c0yax** [comment]
what about when I have generated it and then reopened it

**Comment by bokub** [comment]
Nothing is saved in your browser or computer.
When you close the Vanity-ETH tab, everything disappears.

So when you "reopen" it, nothing else happens.

**Comment by bokub** [comment]
I'm closing the issue. Don't hesitate to ask if you have other questions.
