### ISSUE TITLE
how to use it with GPU?

### ISSUE THREAD

**Issue by thouravi** [bokub/vanity-eth#51]
Hi,

it's currently using CPU to calculate they keys, how can I make it use GPU?

Thanks!

**Comment by bokub** [comment]
Hi,

It's not possible, sorry. Browsers are limited tools.

**Comment by juniorcines** [comment]
> Hi,
> 
> It's not possible, sorry. Browsers are limited tools.

but it is possible to use the GPU.js library to do this using the browser.

It would be nice if it could be used with GPU.

**Comment by bokub** [comment]
Hmmm ok, do you think you can submit a Pull Request then ?

**Comment by juniorcines** [comment]
> Hmmm ok, do you think you can submit a Pull Request then ?

I'm new to github, I don't understand what you mean.

**Comment by bokub** [comment]
OK forget about the pull request, can you show me an example of code to generate an ethereum address using `gpu.js`? I'm new to GPUs 😉

**Comment by juniorcines** [comment]
> 

Well, I'm not an expert in Nodejs, javascript is just that I'm starting.

and the GPU.js library is not used either.

But I would like it to have GPU support.

I used an XMR vanity that supported NVIDIA GPUs and that generated 2.2 Million addresses per second.

That's why I think this vanity eth GPU support will help a lot.

Apart from the web version when using CPU, even if I choose 16 thread, after a while the page stops, also when using 32 thread and everything still gets slow.

**Comment by juniorcines** [comment]
> OK forget about the pull request, can you show me an example of code to generate an ethereum address using GPU.js? I'm new to GPUs 😉

Well, I'm not an expert in Nodejs, javascript is just that I'm starting.

and the GPU.js library is not used either.

But I would like it to have GPU support.

I used an XMR vanity that supported NVIDIA GPUs and that generated 2.2 Million addresses per second.

That's why I think this vanity eth GPU support will help a lot.

Apart from the web version when using CPU, even if I choose 16 thread, after a while the page stops, also when using 32 thread and everything still gets slow.

**Comment by bokub** [comment]
> But I would like it to have GPU support.

Me too, but I don't have the skills / time / motivation for such a complex feature (don't forget that I work on this project alone and for free). If someone wants to work on GPU support, I'd be more than happy to add the feature to Vanity-ETH, but I do not plan to work on it myself.

> I used an XMR vanity that supported NVIDIA GPUs and that generated 2.2 Million addresses per second.

Good for you. There are other vanity address generators for ethereum addresses, they just don't work in the browser. Do your research and use them instead!
